spring:
  datasource:
    url: jdbc:mariadb://mewsinsa-mariadb.cnwmkucoaa34.ap-northeast-2.rds.amazonaws.com:3306/mewsinsa_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: mewsinsa_admin
    password: mewsinsa
  messages:
    basename: messages

mybatis:
  type-aliases-package: com.mewsinsa.*.domain
  mapper-locations: mybatis/**.xml

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8